boxes = [
  # windows server 2025
  { :name => "GOAD-DC01",  :ip => "{{ip_range}}.10", :box => "gusztavvargadr/windows-server-2025-standard", :os => "windows", :cpus => 2, :mem => 3000},
  # windows server 2025
  { :name => "GOAD-DC02",  :ip => "{{ip_range}}.11", :box => "gusztavvargadr/windows-server-2025-standard", :os => "windows", :cpus => 2, :mem => 3000},
  # windows server 2022
  { :name => "GOAD-DC03",  :ip => "{{ip_range}}.12", :box => "StefanScherer/windows_2022", :box_version => "2023.10.15", :os => "windows", :cpus => 2, :mem => 3000},
  # windows server 2025
  { :name => "GOAD-SRV02", :ip => "{{ip_range}}.22", :box => "gusztavvargadr/windows-server-2025-standard", :os => "windows", :cpus => 2, :mem => 6000},
  # windows server 2022
  { :name => "GOAD-SRV03", :ip => "{{ip_range}}.23", :box => "StefanScherer/windows_2022", :box_version => "2023.10.15", :os => "windows", :cpus => 2, :mem => 5000}
]