boxes = [
  { :name => "SCCM-DC",  :ip => "{{ip_range}}.10", :box => "gusztavvargadr/windows-server-2025-standard", :cpus => 2, :mem => 4000, :os => "windows"},
  { :name => "SCCM-MECM" , :ip => "{{ip_range}}.11", :box => "gusztavvargadr/windows-server-2025-standard", :cpus => 2, :mem => 4000, :os => "windows"},
  { :name => "SCCM-MSSQL", :ip => "{{ip_range}}.12", :box => "gusztavvargadr/windows-server-2025-standard", :cpus => 2, :mem => 4000, :os => "windows"},
  { :name => "SCCM-CLIENT",  :ip => "{{ip_range}}.13", :box => "gusztavvargadr/windows-server-2025-standard", :cpus => 2, :mem => 4000, :os => "windows"},
]
