boxes.append(
    { :name => "{{lab_name}}-ELASTIC",
      :ip => "{{ip_range}}.54",
      :box => "bento/ubuntu-22.04",
      :os => "linux",
      :cpus => 2,
      :mem => 8000,
      :forwarded_port => [ {:guest => 22, :host => 2214, :id => "ssh"} ]
    }
)
