boxes = [
  # windows server 2025
  { :name => "GOAD-Light-DC01",  :ip => "{{ip_range}}.10", :box => "gusztavvargadr/windows-server-2025-standard", :os => "windows", :cpus => 2, :mem => 3000},
  # windows server 2025
  { :name => "GOAD-Light-DC02",  :ip => "{{ip_range}}.11", :box => "gusztavvargadr/windows-server-2025-standard", :os => "windows", :cpus => 2, :mem => 3000},
  # windows server 2025
  { :name => "GOAD-Light-SRV02", :ip => "{{ip_range}}.22", :box => "gusztavvargadr/windows-server-2025-standard", :os => "windows", :cpus => 2, :mem => 6000},
]