boxes = [
  { :name => "NHA-DC01",   :ip => "{{ip_range}}.10", :box => "gusztavvargadr/windows-server-2025-standard", :os => "windows", :cpus => "2", :mem => "3000"},
  { :name => "NHA-DC02",   :ip => "{{ip_range}}.20", :box => "gusztavvargadr/windows-server-2025-standard", :os => "windows", :cpus => "2", :mem => "3000"},
  { :name => "NHA-SRV01",  :ip => "{{ip_range}}.21", :box => "gusztavvargadr/windows-server-2025-standard", :os => "windows", :cpus => "2", :mem => "5000"},
  { :name => "NHA-SRV02",  :ip => "{{ip_range}}.22", :box => "gusztavvargadr/windows-server-2025-standard", :os => "windows", :cpus => "2", :mem => "5000"},
  { :name => "NHA-SRV03",  :ip => "{{ip_range}}.23", :box => "gusztavvargadr/windows-server-2025-standard", :os => "windows", :cpus => "2", :mem => "3000"}
]
