boxes = [
  # windows server 2025
  { :name => "GOAD-DC01",  :ip => "{{ip_range}}.10", :box => "gusztavvargadr/windows-server-2025-standard", :os => "windows", :cpus => 2, :mem => 3000},
  # windows server 2025
  { :name => "GOAD-DC02",  :ip => "{{ip_range}}.11", :box => "gusztavvargadr/windows-server-2025-standard", :os => "windows", :cpus => 2, :mem => 3000},
  # windows server 2022
  { :name => "GOAD-DC03",  :ip => "{{ip_range}}.12", :box => "StefanScherer/windows_2022", :box_version => "2023.10.15", :os => "windows", :cpus => 2, :mem => 3000},
  # windows server 2025
  { :name => "GOAD-SRV02", :ip => "{{ip_range}}.22", :box => "gusztavvargadr/windows-server-2025-standard", :os => "windows", :cpus => 2, :mem => 6000},
  # windows server 2022
  { :name => "GOAD-SRV03", :ip => "{{ip_range}}.23", :box => "StefanScherer/windows_2022", :box_version => "2023.10.15", :os => "windows", :cpus => 2, :mem => 5000},
  # windows server 2012 R2 - legacy server (oldest available with automation support)
  { :name => "GOAD-SRV04", :ip => "{{ip_range}}.24", :box => "gusztavvargadr/windows-server-2012-r2-standard", :os => "windows", :cpus => 2, :mem => 2048},
  # windows 10 workstation
  { :name => "GOAD-WS02",  :ip => "{{ip_range}}.32", :box => "gusztavvargadr/windows-10", :os => "windows", :cpus => 2, :mem => 4000},
  # wazuh EDR server
  { :name => "GOAD-WAZUH", :ip => "{{ip_range}}.51", :box => "bento/ubuntu-22.04", :os => "linux", :cpus => 2, :mem => 8000, :forwarded_port => [ {:guest => 22, :host => 2210, :id => "ssh"} ]}
]
{% if not replace_debian_router|default(false) %}
# Lab perimeter (NAT / ip_forward). Omitted when sophos_xgs is enabled.
boxes.append(
    { :name => "{{lab_name}}-ROUTER",
      :ip => "{{ip_range}}.53",
      :box => "bento/debian-12",
      :os => "linux",
      :cpus => 1,
      :mem => 1024,
      :forwarded_port => [ {:guest => 22, :host => 2253, :id => "ssh"} ]
    }
)
{% endif %}