boxes = [
  { :name => "DC01",  :ip => "{{ip_range}}.30", :box => "gusztavvargadr/windows-server-2025-standard", :os => "windows", :cpus => 2, :mem => 4000},
  { :name => "WS01",  :ip => "{{ip_range}}.31", :box => "gusztavvargadr/windows-11", :os => "windows", :cpus => 2, :mem => 4000}
]
