# Wazuh agent installation package URL
# Version 4.10+ required for Windows Server 2025 SCA support
wazuh_agent_install_package: "https://packages.wazuh.com/4.x/windows/wazuh-agent-4.10.2-1.msi"

wazuh_install_location: "c:\\tmp"
